"""Create the database-first V1 schema.

Revision ID: 20260915_0001
Revises:
Create Date: 2026-09-15
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Text

from alembic import op

revision: str = "20260915_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("actor_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=128), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("is_dry_run", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                "SKIPPED_DRY_RUN",
                name="audit_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "before_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_correlation_id"), "audit_logs", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_type"), "audit_logs", ["entity_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_status"), "audit_logs", ["status"], unique=False)
    op.create_table(
        "designs",
        sa.Column("design_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("theme", sa.String(length=128), nullable=True),
        sa.Column("sub_theme", sa.String(length=128), nullable=True),
        sa.Column("image_path", sa.String(length=1024), nullable=True),
        sa.Column("is_customizable", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("requires_manual_review", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("special_handling_notes", sa.Text(), nullable=True),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_designs")),
    )
    op.create_index(op.f("ix_designs_design_code"), "designs", ["design_code"], unique=True)
    op.create_index(op.f("ix_designs_sub_theme"), "designs", ["sub_theme"], unique=False)
    op.create_index(op.f("ix_designs_theme"), "designs", ["theme"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column(
            "import_type",
            sa.Enum(
                "FACTORY_QUOTE",
                "PRODUCT_MASTER",
                "TEMU_LISTING",
                "PRICING_QUOTE",
                "STOCK_ORDER",
                "LABEL",
                "FINANCE",
                name="import_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_file_name", sa.String(length=512), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "COMPLETED_WITH_ERRORS",
                "FAILED",
                name="import_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("row_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("success_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_report_path", sa.String(length=1024), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_correlation_id"), "import_batches", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_import_type"), "import_batches", ["import_type"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_source_sha256"), "import_batches", ["source_sha256"], unique=False
    )
    op.create_index(op.f("ix_import_batches_status"), "import_batches", ["status"], unique=False)
    op.create_table(
        "pricing_rule_sets",
        sa.Column("rule_code", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("min_margin", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("target_margin", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("negotiation_strategy", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_pricing_rule_sets_effective_date_order"),
        ),
        sa.CheckConstraint(
            "min_margin >= 0 AND min_margin < 1", name=op.f("ck_pricing_rule_sets_min_margin_range")
        ),
        sa.CheckConstraint(
            "target_margin > min_margin AND target_margin < 1",
            name=op.f("ck_pricing_rule_sets_margin_order"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_rule_sets")),
        sa.UniqueConstraint("rule_code", "version", name="uq_pricing_rule_sets_code_version"),
    )
    op.create_index(
        op.f("ix_pricing_rule_sets_is_active"), "pricing_rule_sets", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_rule_sets_rule_code"), "pricing_rule_sets", ["rule_code"], unique=False
    )
    op.create_table(
        "suppliers",
        sa.Column("supplier_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "contact",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
    )
    op.create_index(op.f("ix_suppliers_supplier_code"), "suppliers", ["supplier_code"], unique=True)
    op.create_table(
        "products",
        sa.Column("design_id", sa.Uuid(), nullable=False),
        sa.Column("internal_product_code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "READY",
                "LISTED",
                "INACTIVE",
                "ARCHIVED",
                name="product_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["designs.id"],
            name=op.f("fk_products_design_id_designs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("id", "design_id", name="uq_products_id_design_id"),
    )
    op.create_index(op.f("ix_products_design_id"), "products", ["design_id"], unique=False)
    op.create_index(
        op.f("ix_products_internal_product_code"),
        "products",
        ["internal_product_code"],
        unique=True,
    )
    op.create_index(op.f("ix_products_status"), "products", ["status"], unique=False)
    op.create_table(
        "stock_orders",
        sa.Column("stock_order_code", sa.String(length=128), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "IMPORTED",
                "MATCHING",
                "WAITING_LABEL",
                "VALIDATION_FAILED",
                "READY_FOR_SUPPLIER",
                "PRINTED",
                "READY_FOR_SHIPMENT",
                "SHIPPED",
                "CANCELLED",
                name="stock_order_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="IMPORTED",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "API",
                "EXCEL",
                "MANUAL",
                "BROWSER",
                name="stock_order_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("delivery_due_date", sa.Date(), nullable=True),
        sa.Column("carton_count", sa.Integer(), nullable=True),
        sa.Column("units_per_carton", sa.Integer(), nullable=True),
        sa.Column("supplier_workbook_path", sa.String(length=1024), nullable=True),
        sa.Column("print_package_path", sa.String(length=1024), nullable=True),
        sa.Column("validation_report_path", sa.String(length=1024), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "carton_count IS NULL OR carton_count > 0",
            name=op.f("ck_stock_orders_carton_count_positive"),
        ),
        sa.CheckConstraint(
            "units_per_carton IS NULL OR units_per_carton > 0",
            name=op.f("ck_stock_orders_units_per_carton_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_stock_orders_import_batch_id_import_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_stock_orders_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_orders")),
    )
    op.create_index(
        op.f("ix_stock_orders_import_batch_id"), "stock_orders", ["import_batch_id"], unique=False
    )
    op.create_index(op.f("ix_stock_orders_status"), "stock_orders", ["status"], unique=False)
    op.create_index(
        op.f("ix_stock_orders_stock_order_code"), "stock_orders", ["stock_order_code"], unique=True
    )
    op.create_index(
        op.f("ix_stock_orders_supplier_id"), "stock_orders", ["supplier_id"], unique=False
    )
    op.create_table(
        "shipments",
        sa.Column("stock_order_id", sa.Uuid(), nullable=False),
        sa.Column("shipment_code", sa.String(length=128), nullable=False),
        sa.Column("carrier", sa.String(length=64), nullable=False),
        sa.Column("tracking_number", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "READY_FOR_SHIPMENT",
                "SHIPPED",
                "DELIVERED",
                "EXCEPTION",
                name="shipment_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="READY_FOR_SHIPMENT",
            nullable=False,
        ),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("carton_count", sa.Integer(), nullable=False),
        sa.Column("manually_recorded_by", sa.String(length=128), nullable=False),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("carton_count > 0", name=op.f("ck_shipments_carton_count_positive")),
        sa.ForeignKeyConstraint(
            ["stock_order_id"],
            ["stock_orders.id"],
            name=op.f("fk_shipments_stock_order_id_stock_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("carrier", "tracking_number", name="uq_shipments_carrier_tracking"),
    )
    op.create_index(op.f("ix_shipments_shipment_code"), "shipments", ["shipment_code"], unique=True)
    op.create_index(op.f("ix_shipments_status"), "shipments", ["status"], unique=False)
    op.create_index(
        op.f("ix_shipments_stock_order_id"), "shipments", ["stock_order_id"], unique=False
    )
    op.create_table(
        "skus",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("design_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("factory_sku", sa.String(length=128), nullable=False),
        sa.Column("temu_sku", sa.String(length=128), nullable=True),
        sa.Column("size_label", sa.String(length=64), nullable=False),
        sa.Column("width_cm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("height_cm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("colors_count", sa.Integer(), nullable=False),
        sa.Column("framed", sa.Boolean(), nullable=False),
        sa.Column("image_path", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("colors_count > 0", name=op.f("ck_skus_colors_count_positive")),
        sa.CheckConstraint("height_cm > 0", name=op.f("ck_skus_height_cm_positive")),
        sa.CheckConstraint("width_cm > 0", name=op.f("ck_skus_width_cm_positive")),
        sa.ForeignKeyConstraint(
            ["product_id", "design_id"],
            ["products.id", "products.design_id"],
            name="fk_skus_product_design_products",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_skus_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skus")),
        sa.UniqueConstraint("id", "design_id", name="uq_skus_id_design_id"),
        sa.UniqueConstraint(
            "supplier_id",
            "design_id",
            "width_cm",
            "height_cm",
            "colors_count",
            "framed",
            name="uq_skus_supplier_design_variant",
        ),
        sa.UniqueConstraint("supplier_id", "factory_sku", name="uq_skus_supplier_factory_sku"),
    )
    op.create_index(op.f("ix_skus_colors_count"), "skus", ["colors_count"], unique=False)
    op.create_index(op.f("ix_skus_design_id"), "skus", ["design_id"], unique=False)
    op.create_index(op.f("ix_skus_factory_sku"), "skus", ["factory_sku"], unique=False)
    op.create_index(op.f("ix_skus_framed"), "skus", ["framed"], unique=False)
    op.create_index(op.f("ix_skus_product_id"), "skus", ["product_id"], unique=False)
    op.create_index(op.f("ix_skus_supplier_id"), "skus", ["supplier_id"], unique=False)
    op.create_index(op.f("ix_skus_temu_sku"), "skus", ["temu_sku"], unique=True)
    op.create_table(
        "factory_costs",
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("colors_count", sa.Integer(), nullable=False),
        sa.Column("source_size_label", sa.String(length=128), nullable=False),
        sa.Column("width_cm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("height_cm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("framed", sa.Boolean(), nullable=False),
        sa.Column("base_product_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("customization_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("label_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("packaging_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("domestic_shipping_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("other_variable_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("total_variable_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="CNY", nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "validation_status",
            sa.Enum(
                "PENDING",
                "VALID",
                "MANUAL_REVIEW",
                "INVALID",
                name="factory_cost_validation_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("source_sheet", sa.String(length=255), nullable=True),
        sa.Column("source_row", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_product_cost >= 0", name=op.f("ck_factory_costs_base_product_cost_nonnegative")
        ),
        sa.CheckConstraint("colors_count > 0", name=op.f("ck_factory_costs_colors_count_positive")),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_factory_costs_effective_date_order"),
        ),
        sa.CheckConstraint("height_cm > 0", name=op.f("ck_factory_costs_height_cm_positive")),
        sa.CheckConstraint("width_cm > 0", name=op.f("ck_factory_costs_width_cm_positive")),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_factory_costs_import_batch_id_import_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_factory_costs_sku_id_skus"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_factory_costs_supplier_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factory_costs")),
        sa.UniqueConstraint(
            "supplier_id",
            "colors_count",
            "width_cm",
            "height_cm",
            "framed",
            "effective_from",
            name="uq_factory_costs_supplier_variant_effective",
        ),
    )
    op.create_index(
        op.f("ix_factory_costs_effective_from"), "factory_costs", ["effective_from"], unique=False
    )
    op.create_index(
        op.f("ix_factory_costs_import_batch_id"), "factory_costs", ["import_batch_id"], unique=False
    )
    op.create_index(op.f("ix_factory_costs_sku_id"), "factory_costs", ["sku_id"], unique=False)
    op.create_index(
        op.f("ix_factory_costs_supplier_id"), "factory_costs", ["supplier_id"], unique=False
    )
    op.create_index(
        op.f("ix_factory_costs_validation_status"),
        "factory_costs",
        ["validation_status"],
        unique=False,
    )
    op.create_table(
        "stock_order_items",
        sa.Column("stock_order_id", sa.Uuid(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("source_temu_sku", sa.String(length=128), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=True),
        sa.Column("design_id", sa.Uuid(), nullable=True),
        sa.Column("factory_sku_snapshot", sa.String(length=128), nullable=True),
        sa.Column("design_code_snapshot", sa.String(length=64), nullable=True),
        sa.Column("temu_sku_snapshot", sa.String(length=128), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("units_per_carton", sa.Integer(), nullable=True),
        sa.Column("carton_count", sa.Integer(), nullable=True),
        sa.Column("image_filename", sa.String(length=512), nullable=True),
        sa.Column(
            "match_status",
            sa.Enum(
                "PENDING",
                "VALID",
                "MANUAL_REVIEW",
                "INVALID",
                name="stock_item_match_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(sku_id IS NULL AND design_id IS NULL) OR "
            "(sku_id IS NOT NULL AND design_id IS NOT NULL)",
            name=op.f("ck_stock_order_items_sku_design_pair"),
        ),
        sa.CheckConstraint(
            "carton_count IS NULL OR carton_count > 0",
            name=op.f("ck_stock_order_items_carton_count_positive"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_order_items_quantity_positive")),
        sa.CheckConstraint(
            "units_per_carton IS NULL OR units_per_carton > 0",
            name=op.f("ck_stock_order_items_units_per_carton_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["sku_id", "design_id"],
            ["skus.id", "skus.design_id"],
            name="fk_stock_order_items_sku_design_skus",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stock_order_id"],
            ["stock_orders.id"],
            name=op.f("fk_stock_order_items_stock_order_id_stock_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_order_items")),
        sa.UniqueConstraint(
            "stock_order_id", "line_number", name="uq_stock_order_items_order_line"
        ),
    )
    op.create_index(
        op.f("ix_stock_order_items_design_id"), "stock_order_items", ["design_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_order_items_match_status"),
        "stock_order_items",
        ["match_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_order_items_sku_id"), "stock_order_items", ["sku_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_order_items_source_temu_sku"),
        "stock_order_items",
        ["source_temu_sku"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_order_items_stock_order_id"),
        "stock_order_items",
        ["stock_order_id"],
        unique=False,
    )
    op.create_table(
        "temu_listings",
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("store_code", sa.String(length=64), nullable=False),
        sa.Column("marketplace", sa.String(length=16), server_default="US", nullable=False),
        sa.Column("temu_spu", sa.String(length=128), nullable=True),
        sa.Column("temu_goods_id", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "ACTIVE",
                "REJECTED",
                "INACTIVE",
                "UNKNOWN",
                name="listing_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["skus.id"], name=op.f("fk_temu_listings_sku_id_skus"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_temu_listings")),
        sa.UniqueConstraint("id", "sku_id", name="uq_temu_listings_id_sku_id"),
        sa.UniqueConstraint("store_code", "sku_id", name="uq_temu_listings_store_sku"),
        sa.UniqueConstraint("store_code", "temu_goods_id", name="uq_temu_listings_store_goods"),
        sa.UniqueConstraint(
            "store_code", "temu_spu", "sku_id", name="uq_temu_listings_store_spu_sku"
        ),
    )
    op.create_index(op.f("ix_temu_listings_sku_id"), "temu_listings", ["sku_id"], unique=False)
    op.create_index(op.f("ix_temu_listings_status"), "temu_listings", ["status"], unique=False)
    op.create_index(
        op.f("ix_temu_listings_store_code"), "temu_listings", ["store_code"], unique=False
    )
    op.create_index(
        op.f("ix_temu_listings_temu_goods_id"), "temu_listings", ["temu_goods_id"], unique=False
    )
    op.create_index(op.f("ix_temu_listings_temu_spu"), "temu_listings", ["temu_spu"], unique=False)
    op.create_table(
        "financial_transactions",
        sa.Column("sku_id", sa.Uuid(), nullable=True),
        sa.Column("design_id", sa.Uuid(), nullable=True),
        sa.Column("temu_listing_id", sa.Uuid(), nullable=True),
        sa.Column("stock_order_item_id", sa.Uuid(), nullable=True),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "REVENUE",
                "SETTLEMENT_INCOME",
                "FACTORY_COST",
                "CUSTOMIZATION_COST",
                "PACKAGING_COST",
                "SHIPPING_COST",
                "LABEL_COST",
                "REFUND",
                "OTHER_COST",
                name="financial_transaction_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("settlement_reference", sa.String(length=128), nullable=True),
        sa.Column("external_reference", sa.String(length=256), nullable=True),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "API",
                "EXCEL",
                "MANUAL",
                "BROWSER",
                name="finance_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "match_status",
            sa.Enum(
                "PENDING",
                "VALID",
                "MANUAL_REVIEW",
                "INVALID",
                name="finance_match_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(sku_id IS NULL AND design_id IS NULL) OR "
            "(sku_id IS NOT NULL AND design_id IS NOT NULL)",
            name=op.f("ck_financial_transactions_sku_design_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_financial_transactions_import_batch_id_import_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id", "design_id"],
            ["skus.id", "skus.design_id"],
            name="fk_financial_transactions_sku_design_skus",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stock_order_item_id"],
            ["stock_order_items.id"],
            name=op.f("fk_financial_transactions_stock_order_item_id_stock_order_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["temu_listing_id"],
            ["temu_listings.id"],
            name=op.f("fk_financial_transactions_temu_listing_id_temu_listings"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_transactions")),
    )
    op.create_index(
        op.f("ix_financial_transactions_design_id"),
        "financial_transactions",
        ["design_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_external_reference"),
        "financial_transactions",
        ["external_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_idempotency_key"),
        "financial_transactions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_financial_transactions_import_batch_id"),
        "financial_transactions",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_match_status"),
        "financial_transactions",
        ["match_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_occurred_at"),
        "financial_transactions",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_settlement_reference"),
        "financial_transactions",
        ["settlement_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_sku_id"), "financial_transactions", ["sku_id"], unique=False
    )
    op.create_index(
        op.f("ix_financial_transactions_stock_order_item_id"),
        "financial_transactions",
        ["stock_order_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_temu_listing_id"),
        "financial_transactions",
        ["temu_listing_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_transactions_transaction_type"),
        "financial_transactions",
        ["transaction_type"],
        unique=False,
    )
    op.create_table(
        "labels",
        sa.Column("stock_order_id", sa.Uuid(), nullable=False),
        sa.Column("stock_order_item_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("design_id", sa.Uuid(), nullable=False),
        sa.Column(
            "label_type",
            sa.Enum(
                "PRODUCT_BARCODE",
                "SKU_LABEL",
                "TEMU_PRODUCT_LABEL",
                "CARTON_LABEL",
                "COMPLIANCE_LABEL",
                "OTHER",
                name="label_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING_LABEL",
                "READY",
                "PRINTED",
                "ERROR",
                name="label_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="WAITING_LABEL",
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=1024), nullable=True),
        sa.Column("original_file_path", sa.String(length=1024), nullable=True),
        sa.Column("media_type", sa.String(length=128), nullable=True),
        sa.Column("page_size", sa.String(length=64), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("required_quantity", sa.Integer(), nullable=False),
        sa.Column("planned_print_quantity", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("printed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "planned_print_quantity >= 0", name=op.f("ck_labels_planned_print_quantity_nonnegative")
        ),
        sa.CheckConstraint(
            "required_quantity >= 0", name=op.f("ck_labels_required_quantity_nonnegative")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_labels_version_positive")),
        sa.ForeignKeyConstraint(
            ["sku_id", "design_id"],
            ["skus.id", "skus.design_id"],
            name="fk_labels_sku_design_skus",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stock_order_id"],
            ["stock_orders.id"],
            name=op.f("fk_labels_stock_order_id_stock_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_order_item_id"],
            ["stock_order_items.id"],
            name=op.f("fk_labels_stock_order_item_id_stock_order_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labels")),
        sa.UniqueConstraint(
            "stock_order_item_id", "label_type", "version", name="uq_labels_item_type_version"
        ),
    )
    op.create_index(op.f("ix_labels_design_id"), "labels", ["design_id"], unique=False)
    op.create_index(op.f("ix_labels_label_type"), "labels", ["label_type"], unique=False)
    op.create_index(op.f("ix_labels_sha256"), "labels", ["sha256"], unique=False)
    op.create_index(op.f("ix_labels_sku_id"), "labels", ["sku_id"], unique=False)
    op.create_index(op.f("ix_labels_status"), "labels", ["status"], unique=False)
    op.create_index(op.f("ix_labels_stock_order_id"), "labels", ["stock_order_id"], unique=False)
    op.create_index(
        op.f("ix_labels_stock_order_item_id"), "labels", ["stock_order_item_id"], unique=False
    )
    op.create_table(
        "pricing_quotes",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=True),
        sa.Column("external_quote_id", sa.String(length=128), nullable=True),
        sa.Column("quote_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "API",
                "EXCEL",
                "MANUAL",
                "BROWSER",
                name="quote_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quoted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quote_price > 0", name=op.f("ck_pricing_quotes_quote_price_positive")),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_pricing_quotes_import_batch_id_import_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id", "sku_id"],
            ["temu_listings.id", "temu_listings.sku_id"],
            name="fk_pricing_quotes_listing_sku_temu_listings",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_quotes")),
        sa.UniqueConstraint("id", "sku_id", name="uq_pricing_quotes_id_sku_id"),
        sa.UniqueConstraint(
            "listing_id", "external_quote_id", name="uq_pricing_quotes_listing_external_quote"
        ),
    )
    op.create_index(
        op.f("ix_pricing_quotes_import_batch_id"),
        "pricing_quotes",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_quotes_listing_id"), "pricing_quotes", ["listing_id"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_quotes_quoted_at"), "pricing_quotes", ["quoted_at"], unique=False
    )
    op.create_index(op.f("ix_pricing_quotes_sku_id"), "pricing_quotes", ["sku_id"], unique=False)
    op.create_table(
        "pricing_decisions",
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=False),
        sa.Column("factory_cost_id", sa.Uuid(), nullable=True),
        sa.Column("pricing_rule_set_id", sa.Uuid(), nullable=False),
        sa.Column("quote_price_snapshot", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("variable_cost_snapshot", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("gross_margin", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("min_margin", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("target_margin", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("minimum_acceptable_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "ACCEPT",
                "NEGOTIATE",
                "REJECT",
                "MANUAL_REVIEW",
                name="pricing_decision_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("negotiation_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("rule_version_snapshot", sa.String(length=64), nullable=False),
        sa.Column("is_dry_run", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("execution_adapter", sa.String(length=128), nullable=True),
        sa.Column(
            "execution_status",
            sa.Enum(
                "NOT_REQUESTED",
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                "SKIPPED_DRY_RUN",
                name="pricing_execution_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="NOT_REQUESTED",
            nullable=False,
        ),
        sa.Column(
            "execution_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("execution_error", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gross_margin IS NULL OR gross_margin < 1",
            name=op.f("ck_pricing_decisions_gross_margin_range"),
        ),
        sa.CheckConstraint(
            "min_margin >= 0 AND min_margin < 1", name=op.f("ck_pricing_decisions_min_margin_range")
        ),
        sa.CheckConstraint(
            "quote_price_snapshot > 0", name=op.f("ck_pricing_decisions_quote_price_positive")
        ),
        sa.CheckConstraint(
            "target_margin > min_margin AND target_margin < 1",
            name=op.f("ck_pricing_decisions_margin_order"),
        ),
        sa.CheckConstraint(
            "variable_cost_snapshot IS NULL OR variable_cost_snapshot >= 0",
            name=op.f("ck_pricing_decisions_variable_cost_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["factory_cost_id"],
            ["factory_costs.id"],
            name=op.f("fk_pricing_decisions_factory_cost_id_factory_costs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pricing_rule_set_id"],
            ["pricing_rule_sets.id"],
            name=op.f("fk_pricing_decisions_pricing_rule_set_id_pricing_rule_sets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["quote_id", "sku_id"],
            ["pricing_quotes.id", "pricing_quotes.sku_id"],
            name="fk_pricing_decisions_quote_sku_pricing_quotes",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_decisions")),
    )
    op.create_index(
        op.f("ix_pricing_decisions_decision"), "pricing_decisions", ["decision"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_decisions_execution_status"),
        "pricing_decisions",
        ["execution_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_decisions_factory_cost_id"),
        "pricing_decisions",
        ["factory_cost_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_decisions_pricing_rule_set_id"),
        "pricing_decisions",
        ["pricing_rule_set_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_decisions_quote_id"), "pricing_decisions", ["quote_id"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_decisions_sku_id"), "pricing_decisions", ["sku_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pricing_decisions_sku_id"), table_name="pricing_decisions")
    op.drop_index(op.f("ix_pricing_decisions_quote_id"), table_name="pricing_decisions")
    op.drop_index(op.f("ix_pricing_decisions_pricing_rule_set_id"), table_name="pricing_decisions")
    op.drop_index(op.f("ix_pricing_decisions_factory_cost_id"), table_name="pricing_decisions")
    op.drop_index(op.f("ix_pricing_decisions_execution_status"), table_name="pricing_decisions")
    op.drop_index(op.f("ix_pricing_decisions_decision"), table_name="pricing_decisions")
    op.drop_table("pricing_decisions")
    op.drop_index(op.f("ix_pricing_quotes_sku_id"), table_name="pricing_quotes")
    op.drop_index(op.f("ix_pricing_quotes_quoted_at"), table_name="pricing_quotes")
    op.drop_index(op.f("ix_pricing_quotes_listing_id"), table_name="pricing_quotes")
    op.drop_index(op.f("ix_pricing_quotes_import_batch_id"), table_name="pricing_quotes")
    op.drop_table("pricing_quotes")
    op.drop_index(op.f("ix_labels_stock_order_item_id"), table_name="labels")
    op.drop_index(op.f("ix_labels_stock_order_id"), table_name="labels")
    op.drop_index(op.f("ix_labels_status"), table_name="labels")
    op.drop_index(op.f("ix_labels_sku_id"), table_name="labels")
    op.drop_index(op.f("ix_labels_sha256"), table_name="labels")
    op.drop_index(op.f("ix_labels_label_type"), table_name="labels")
    op.drop_index(op.f("ix_labels_design_id"), table_name="labels")
    op.drop_table("labels")
    op.drop_index(
        op.f("ix_financial_transactions_transaction_type"), table_name="financial_transactions"
    )
    op.drop_index(
        op.f("ix_financial_transactions_temu_listing_id"), table_name="financial_transactions"
    )
    op.drop_index(
        op.f("ix_financial_transactions_stock_order_item_id"), table_name="financial_transactions"
    )
    op.drop_index(op.f("ix_financial_transactions_sku_id"), table_name="financial_transactions")
    op.drop_index(
        op.f("ix_financial_transactions_settlement_reference"), table_name="financial_transactions"
    )
    op.drop_index(
        op.f("ix_financial_transactions_occurred_at"), table_name="financial_transactions"
    )
    op.drop_index(
        op.f("ix_financial_transactions_match_status"), table_name="financial_transactions"
    )
    op.drop_index(
        op.f("ix_financial_transactions_import_batch_id"), table_name="financial_transactions"
    )
    op.drop_index(
        op.f("ix_financial_transactions_idempotency_key"), table_name="financial_transactions"
    )
    op.drop_index(
        op.f("ix_financial_transactions_external_reference"), table_name="financial_transactions"
    )
    op.drop_index(op.f("ix_financial_transactions_design_id"), table_name="financial_transactions")
    op.drop_table("financial_transactions")
    op.drop_index(op.f("ix_temu_listings_temu_spu"), table_name="temu_listings")
    op.drop_index(op.f("ix_temu_listings_temu_goods_id"), table_name="temu_listings")
    op.drop_index(op.f("ix_temu_listings_store_code"), table_name="temu_listings")
    op.drop_index(op.f("ix_temu_listings_status"), table_name="temu_listings")
    op.drop_index(op.f("ix_temu_listings_sku_id"), table_name="temu_listings")
    op.drop_table("temu_listings")
    op.drop_index(op.f("ix_stock_order_items_stock_order_id"), table_name="stock_order_items")
    op.drop_index(op.f("ix_stock_order_items_source_temu_sku"), table_name="stock_order_items")
    op.drop_index(op.f("ix_stock_order_items_sku_id"), table_name="stock_order_items")
    op.drop_index(op.f("ix_stock_order_items_match_status"), table_name="stock_order_items")
    op.drop_index(op.f("ix_stock_order_items_design_id"), table_name="stock_order_items")
    op.drop_table("stock_order_items")
    op.drop_index(op.f("ix_factory_costs_validation_status"), table_name="factory_costs")
    op.drop_index(op.f("ix_factory_costs_supplier_id"), table_name="factory_costs")
    op.drop_index(op.f("ix_factory_costs_sku_id"), table_name="factory_costs")
    op.drop_index(op.f("ix_factory_costs_import_batch_id"), table_name="factory_costs")
    op.drop_index(op.f("ix_factory_costs_effective_from"), table_name="factory_costs")
    op.drop_table("factory_costs")
    op.drop_index(op.f("ix_skus_temu_sku"), table_name="skus")
    op.drop_index(op.f("ix_skus_supplier_id"), table_name="skus")
    op.drop_index(op.f("ix_skus_product_id"), table_name="skus")
    op.drop_index(op.f("ix_skus_framed"), table_name="skus")
    op.drop_index(op.f("ix_skus_factory_sku"), table_name="skus")
    op.drop_index(op.f("ix_skus_design_id"), table_name="skus")
    op.drop_index(op.f("ix_skus_colors_count"), table_name="skus")
    op.drop_table("skus")
    op.drop_index(op.f("ix_shipments_stock_order_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_status"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_shipment_code"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(op.f("ix_stock_orders_supplier_id"), table_name="stock_orders")
    op.drop_index(op.f("ix_stock_orders_stock_order_code"), table_name="stock_orders")
    op.drop_index(op.f("ix_stock_orders_status"), table_name="stock_orders")
    op.drop_index(op.f("ix_stock_orders_import_batch_id"), table_name="stock_orders")
    op.drop_table("stock_orders")
    op.drop_index(op.f("ix_products_status"), table_name="products")
    op.drop_index(op.f("ix_products_internal_product_code"), table_name="products")
    op.drop_index(op.f("ix_products_design_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_suppliers_supplier_code"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_pricing_rule_sets_rule_code"), table_name="pricing_rule_sets")
    op.drop_index(op.f("ix_pricing_rule_sets_is_active"), table_name="pricing_rule_sets")
    op.drop_table("pricing_rule_sets")
    op.drop_index(op.f("ix_import_batches_status"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_source_sha256"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_import_type"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_correlation_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_designs_theme"), table_name="designs")
    op.drop_index(op.f("ix_designs_sub_theme"), table_name="designs")
    op.drop_index(op.f("ix_designs_design_code"), table_name="designs")
    op.drop_table("designs")
    op.drop_index(op.f("ix_audit_logs_status"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
