"""add fangguo sales order read model

Revision ID: 72fb575f576e
Revises: d9b1f737a5bc
Create Date: 2026-09-21 02:28:02.011471
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "72fb575f576e"
down_revision: str | None = "d9b1f737a5bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_orders",
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("source_connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_order_id", sa.String(length=255), nullable=False),
        sa.Column("provider_record_id", sa.String(length=255), nullable=True),
        sa.Column("system_order_id", sa.String(length=255), nullable=True),
        sa.Column("platform_code", sa.Integer(), nullable=False),
        sa.Column("platform_description", sa.String(length=128), nullable=True),
        sa.Column("order_type", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DISCOVERED",
                "PROCESSING",
                "SHIPPED",
                "COMPLETED",
                "CANCELLED",
                "UNKNOWN",
                name="sales_order_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="DISCOVERED",
            nullable=False,
        ),
        sa.Column("external_status_description", sa.String(length=128), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_amount IS NULL OR total_amount >= 0",
            name=op.f("ck_sales_orders_total_amount_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["source_connection_id"],
            ["integration_connections.id"],
            name=op.f("fk_sales_orders_source_connection_id_integration_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_sales_orders_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_orders")),
        sa.UniqueConstraint(
            "source_connection_id",
            "external_order_id",
            name="uq_sales_orders_connection_external_order",
        ),
    )
    op.create_index(
        op.f("ix_sales_orders_external_order_id"),
        "sales_orders",
        ["external_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_orders_platform_code"), "sales_orders", ["platform_code"], unique=False
    )
    op.create_index(
        op.f("ix_sales_orders_provider_record_id"),
        "sales_orders",
        ["provider_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_orders_source_connection_id"),
        "sales_orders",
        ["source_connection_id"],
        unique=False,
    )
    op.create_index(op.f("ix_sales_orders_status"), "sales_orders", ["status"], unique=False)
    op.create_index(op.f("ix_sales_orders_store_id"), "sales_orders", ["store_id"], unique=False)
    op.create_index(
        op.f("ix_sales_orders_system_order_id"), "sales_orders", ["system_order_id"], unique=False
    )
    op.create_table(
        "fulfillment_orders",
        sa.Column("sales_order_id", sa.Uuid(), nullable=False),
        sa.Column("source_connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_fulfillment_id", sa.String(length=255), nullable=False),
        sa.Column("factory_external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING_ORGANIZATION",
                "WAITING_PUSH",
                "REVERSED",
                "FACTORY_REVIEW",
                "IN_PRODUCTION",
                "PACKED",
                "UNKNOWN",
                name="fangguo_fulfillment_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column("external_status_code", sa.Integer(), nullable=False),
        sa.Column("external_status_description", sa.String(length=128), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
            name=op.f("fk_fulfillment_orders_sales_order_id_sales_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_connection_id"],
            ["integration_connections.id"],
            name=op.f("fk_fulfillment_orders_source_connection_id_integration_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fulfillment_orders")),
    )
    op.create_index(
        op.f("ix_fulfillment_orders_external_fulfillment_id"),
        "fulfillment_orders",
        ["external_fulfillment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fulfillment_orders_external_status_code"),
        "fulfillment_orders",
        ["external_status_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fulfillment_orders_factory_external_id"),
        "fulfillment_orders",
        ["factory_external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fulfillment_orders_sales_order_id"),
        "fulfillment_orders",
        ["sales_order_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_fulfillment_orders_source_connection_id"),
        "fulfillment_orders",
        ["source_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fulfillment_orders_status"), "fulfillment_orders", ["status"], unique=False
    )
    op.create_table(
        "sales_order_items",
        sa.Column("sales_order_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=True),
        sa.Column("temu_listing_id", sa.Uuid(), nullable=True),
        sa.Column("external_line_id", sa.String(length=255), nullable=False),
        sa.Column("provider_item_id", sa.String(length=255), nullable=True),
        sa.Column("external_sku_id", sa.String(length=255), nullable=True),
        sa.Column("external_goods_id", sa.String(length=255), nullable=True),
        sa.Column("seller_sku", sa.String(length=255), nullable=True),
        sa.Column("mapped_sku", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("specification", sa.String(length=512), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column(
            "match_status",
            sa.Enum(
                "PENDING",
                "VALID",
                "MANUAL_REVIEW",
                "INVALID",
                name="sales_order_item_match_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("refund_status_description", sa.String(length=128), nullable=True),
        sa.Column("cancelled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sales_order_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price IS NULL OR unit_price >= 0",
            name=op.f("ck_sales_order_items_unit_price_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
            name=op.f("fk_sales_order_items_sales_order_id_sales_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_sales_order_items_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["temu_listing_id"],
            ["temu_listings.id"],
            name=op.f("fk_sales_order_items_temu_listing_id_temu_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order_items")),
        sa.UniqueConstraint(
            "sales_order_id", "external_line_id", name="uq_sales_order_items_order_line"
        ),
    )
    op.create_index(
        op.f("ix_sales_order_items_external_goods_id"),
        "sales_order_items",
        ["external_goods_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_items_external_sku_id"),
        "sales_order_items",
        ["external_sku_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_items_mapped_sku"), "sales_order_items", ["mapped_sku"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_items_match_status"),
        "sales_order_items",
        ["match_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_items_provider_item_id"),
        "sales_order_items",
        ["provider_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_items_sales_order_id"),
        "sales_order_items",
        ["sales_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_items_seller_sku"), "sales_order_items", ["seller_sku"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_items_sku_id"), "sales_order_items", ["sku_id"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_items_temu_listing_id"),
        "sales_order_items",
        ["temu_listing_id"],
        unique=False,
    )
    op.create_table(
        "sales_order_shipments",
        sa.Column("sales_order_id", sa.Uuid(), nullable=False),
        sa.Column("sales_order_item_id", sa.Uuid(), nullable=True),
        sa.Column("carrier_code", sa.String(length=64), nullable=False),
        sa.Column("tracking_number", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "READY_FOR_SHIPMENT",
                "SHIPPED",
                "DELIVERED",
                "EXCEPTION",
                name="sales_order_shipment_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="SHIPPED",
            nullable=False,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_id"],
            ["sales_orders.id"],
            name=op.f("fk_sales_order_shipments_sales_order_id_sales_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_order_item_id"],
            ["sales_order_items.id"],
            name=op.f("fk_sales_order_shipments_sales_order_item_id_sales_order_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order_shipments")),
        sa.UniqueConstraint(
            "sales_order_id",
            "carrier_code",
            "tracking_number",
            name="uq_sales_order_shipments_order_carrier_tracking",
        ),
    )
    op.create_index(
        op.f("ix_sales_order_shipments_sales_order_id"),
        "sales_order_shipments",
        ["sales_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_shipments_sales_order_item_id"),
        "sales_order_shipments",
        ["sales_order_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_shipments_status"), "sales_order_shipments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_sales_order_shipments_tracking_number"),
        "sales_order_shipments",
        ["tracking_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sales_order_shipments_tracking_number"), table_name="sales_order_shipments"
    )
    op.drop_index(op.f("ix_sales_order_shipments_status"), table_name="sales_order_shipments")
    op.drop_index(
        op.f("ix_sales_order_shipments_sales_order_item_id"), table_name="sales_order_shipments"
    )
    op.drop_index(
        op.f("ix_sales_order_shipments_sales_order_id"), table_name="sales_order_shipments"
    )
    op.drop_table("sales_order_shipments")
    op.drop_index(op.f("ix_sales_order_items_temu_listing_id"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_sku_id"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_seller_sku"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_sales_order_id"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_provider_item_id"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_match_status"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_mapped_sku"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_external_sku_id"), table_name="sales_order_items")
    op.drop_index(op.f("ix_sales_order_items_external_goods_id"), table_name="sales_order_items")
    op.drop_table("sales_order_items")
    op.drop_index(op.f("ix_fulfillment_orders_status"), table_name="fulfillment_orders")
    op.drop_index(
        op.f("ix_fulfillment_orders_source_connection_id"), table_name="fulfillment_orders"
    )
    op.drop_index(op.f("ix_fulfillment_orders_sales_order_id"), table_name="fulfillment_orders")
    op.drop_index(
        op.f("ix_fulfillment_orders_factory_external_id"), table_name="fulfillment_orders"
    )
    op.drop_index(
        op.f("ix_fulfillment_orders_external_status_code"), table_name="fulfillment_orders"
    )
    op.drop_index(
        op.f("ix_fulfillment_orders_external_fulfillment_id"), table_name="fulfillment_orders"
    )
    op.drop_table("fulfillment_orders")
    op.drop_index(op.f("ix_sales_orders_system_order_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_store_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_status"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_source_connection_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_provider_record_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_platform_code"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_external_order_id"), table_name="sales_orders")
    op.drop_table("sales_orders")
    # ### end Alembic commands ###
