"""add integration automation foundation

Revision ID: d9b1f737a5bc
Revises: 20260918_0004
Create Date: 2026-09-21 02:06:29.208348
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d9b1f737a5bc"
down_revision: str | None = "20260918_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("store_code", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=32), server_default="TEMU", nullable=False),
        sa.Column("marketplace", sa.String(length=16), server_default="US", nullable=False),
        sa.Column(
            "seller_type", sa.String(length=32), server_default="CROSS_BORDER", nullable=False
        ),
        sa.Column(
            "business_model", sa.String(length=32), server_default="SEMI_MANAGED", nullable=False
        ),
        sa.Column("mall_id", sa.String(length=128), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column(
            "timezone", sa.String(length=64), server_default="America/Los_Angeles", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
        sa.UniqueConstraint("platform", "mall_id", name="uq_stores_platform_mall_id"),
    )
    op.create_index(op.f("ix_stores_mall_id"), "stores", ["mall_id"], unique=False)
    op.create_index(op.f("ix_stores_store_code"), "stores", ["store_code"], unique=True)
    op.create_table(
        "integration_connections",
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "TEMU",
                "FANGGUO",
                "DIANXIAOMI",
                name="integration_provider",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("connection_name", sa.String(length=128), nullable=False),
        sa.Column("external_account_id", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_AUTHORIZATION",
                "ACTIVE",
                "EXPIRED",
                "REVOKED",
                "ERROR",
                "DISABLED",
                name="integration_connection_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING_AUTHORIZATION",
            nullable=False,
        ),
        sa.Column("credential_reference", sa.String(length=512), nullable=True),
        sa.Column("token_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_integration_connections_store_id_stores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_connections")),
        sa.UniqueConstraint(
            "store_id",
            "provider",
            "connection_name",
            name="uq_integration_connections_store_provider_name",
        ),
    )
    op.create_index(
        op.f("ix_integration_connections_external_account_id"),
        "integration_connections",
        ["external_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_provider"),
        "integration_connections",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_status"),
        "integration_connections",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_store_id"),
        "integration_connections",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_token_expires_at"),
        "integration_connections",
        ["token_expires_at"],
        unique=False,
    )
    op.create_table(
        "integration_runs",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("run_type", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "INBOUND",
                "OUTBOUND",
                name="integration_direction",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "PARTIAL",
                "FAILED",
                "SKIPPED",
                name="integration_run_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("records_read", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_written", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count > 0", name=op.f("ck_integration_runs_attempt_count_positive")
        ),
        sa.CheckConstraint(
            "records_failed >= 0", name=op.f("ck_integration_runs_records_failed_nonnegative")
        ),
        sa.CheckConstraint(
            "records_read >= 0", name=op.f("ck_integration_runs_records_read_nonnegative")
        ),
        sa.CheckConstraint(
            "records_written >= 0", name=op.f("ck_integration_runs_records_written_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["integration_connections.id"],
            name=op.f("fk_integration_runs_connection_id_integration_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_runs")),
    )
    op.create_index(
        op.f("ix_integration_runs_connection_id"),
        "integration_runs",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_runs_correlation_id"),
        "integration_runs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_runs_idempotency_key"),
        "integration_runs",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_integration_runs_provider_request_id"),
        "integration_runs",
        ["provider_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_runs_resource_type"),
        "integration_runs",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_runs_run_type"), "integration_runs", ["run_type"], unique=False
    )
    op.create_index(
        op.f("ix_integration_runs_status"), "integration_runs", ["status"], unique=False
    )
    op.create_table(
        "integration_sync_cursors",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("cursor_name", sa.String(length=64), nullable=False),
        sa.Column("cursor_value", sa.Text(), nullable=True),
        sa.Column("watermark_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_successful_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "extra_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["integration_connections.id"],
            name=op.f("fk_integration_sync_cursors_connection_id_integration_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_sync_cursors")),
        sa.UniqueConstraint(
            "connection_id",
            "resource_type",
            "cursor_name",
            name="uq_integration_sync_cursors_connection_resource_name",
        ),
    )
    op.create_index(
        op.f("ix_integration_sync_cursors_connection_id"),
        "integration_sync_cursors",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_sync_cursors_resource_type"),
        "integration_sync_cursors",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "platform_events",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("external_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                "IGNORED",
                name="integration_event_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="RECEIVED",
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_platform_events_attempt_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["integration_connections.id"],
            name=op.f("fk_platform_events_connection_id_integration_connections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_events")),
        sa.UniqueConstraint(
            "connection_id",
            "external_event_id",
            name="uq_platform_events_connection_external_event",
        ),
    )
    op.create_index(
        op.f("ix_platform_events_connection_id"), "platform_events", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_platform_events_event_type"), "platform_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_platform_events_status"), "platform_events", ["status"], unique=False)
    op.create_table(
        "platform_assets",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("design_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("sku_id", sa.Uuid(), nullable=True),
        sa.Column("asset_role", sa.String(length=64), nullable=False),
        sa.Column("local_path", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("byte_size", sa.Integer(), nullable=True),
        sa.Column("external_asset_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "UPLOADING",
                "READY",
                "FAILED",
                "EXPIRED",
                name="platform_asset_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "byte_size IS NULL OR byte_size >= 0",
            name=op.f("ck_platform_assets_byte_size_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["integration_connections.id"],
            name=op.f("fk_platform_assets_connection_id_integration_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["design_id"],
            ["designs.id"],
            name=op.f("fk_platform_assets_design_id_designs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_platform_assets_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_platform_assets_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_assets")),
    )
    op.create_index(
        op.f("ix_platform_assets_asset_role"), "platform_assets", ["asset_role"], unique=False
    )
    op.create_index(
        op.f("ix_platform_assets_connection_id"), "platform_assets", ["connection_id"], unique=False
    )
    op.create_index(
        op.f("ix_platform_assets_design_id"), "platform_assets", ["design_id"], unique=False
    )
    op.create_index(
        op.f("ix_platform_assets_external_asset_id"),
        "platform_assets",
        ["external_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_platform_assets_product_id"), "platform_assets", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_platform_assets_sha256"), "platform_assets", ["sha256"], unique=False)
    op.create_index(op.f("ix_platform_assets_sku_id"), "platform_assets", ["sku_id"], unique=False)
    op.create_index(op.f("ix_platform_assets_status"), "platform_assets", ["status"], unique=False)
    op.create_table(
        "listing_submissions",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku_id", sa.Uuid(), nullable=True),
        sa.Column("temu_listing_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "CREATE",
                "UPDATE",
                "STATUS_SYNC",
                "INVENTORY_UPDATE",
                "COMPLIANCE_UPDATE",
                name="listing_submission_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "MANUAL_REVIEW",
                "SKIPPED_DRY_RUN",
                name="listing_submission_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("is_dry_run", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "request_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "response_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count > 0", name=op.f("ck_listing_submissions_attempt_count_positive")
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["integration_connections.id"],
            name=op.f("fk_listing_submissions_connection_id_integration_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_listing_submissions_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"],
            ["skus.id"],
            name=op.f("fk_listing_submissions_sku_id_skus"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["temu_listing_id"],
            ["temu_listings.id"],
            name=op.f("fk_listing_submissions_temu_listing_id_temu_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_submissions")),
    )
    op.create_index(
        op.f("ix_listing_submissions_action"), "listing_submissions", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_listing_submissions_connection_id"),
        "listing_submissions",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_submissions_idempotency_key"),
        "listing_submissions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_listing_submissions_product_id"),
        "listing_submissions",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_submissions_provider_request_id"),
        "listing_submissions",
        ["provider_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_submissions_sku_id"), "listing_submissions", ["sku_id"], unique=False
    )
    op.create_index(
        op.f("ix_listing_submissions_status"), "listing_submissions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_listing_submissions_temu_listing_id"),
        "listing_submissions",
        ["temu_listing_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listing_submissions_temu_listing_id"), table_name="listing_submissions")
    op.drop_index(op.f("ix_listing_submissions_status"), table_name="listing_submissions")
    op.drop_index(op.f("ix_listing_submissions_sku_id"), table_name="listing_submissions")
    op.drop_index(
        op.f("ix_listing_submissions_provider_request_id"), table_name="listing_submissions"
    )
    op.drop_index(op.f("ix_listing_submissions_product_id"), table_name="listing_submissions")
    op.drop_index(op.f("ix_listing_submissions_idempotency_key"), table_name="listing_submissions")
    op.drop_index(op.f("ix_listing_submissions_connection_id"), table_name="listing_submissions")
    op.drop_index(op.f("ix_listing_submissions_action"), table_name="listing_submissions")
    op.drop_table("listing_submissions")
    op.drop_index(op.f("ix_platform_assets_status"), table_name="platform_assets")
    op.drop_index(op.f("ix_platform_assets_sku_id"), table_name="platform_assets")
    op.drop_index(op.f("ix_platform_assets_sha256"), table_name="platform_assets")
    op.drop_index(op.f("ix_platform_assets_product_id"), table_name="platform_assets")
    op.drop_index(op.f("ix_platform_assets_external_asset_id"), table_name="platform_assets")
    op.drop_index(op.f("ix_platform_assets_design_id"), table_name="platform_assets")
    op.drop_index(op.f("ix_platform_assets_connection_id"), table_name="platform_assets")
    op.drop_index(op.f("ix_platform_assets_asset_role"), table_name="platform_assets")
    op.drop_table("platform_assets")
    op.drop_index(op.f("ix_platform_events_status"), table_name="platform_events")
    op.drop_index(op.f("ix_platform_events_event_type"), table_name="platform_events")
    op.drop_index(op.f("ix_platform_events_connection_id"), table_name="platform_events")
    op.drop_table("platform_events")
    op.drop_index(
        op.f("ix_integration_sync_cursors_resource_type"), table_name="integration_sync_cursors"
    )
    op.drop_index(
        op.f("ix_integration_sync_cursors_connection_id"), table_name="integration_sync_cursors"
    )
    op.drop_table("integration_sync_cursors")
    op.drop_index(op.f("ix_integration_runs_status"), table_name="integration_runs")
    op.drop_index(op.f("ix_integration_runs_run_type"), table_name="integration_runs")
    op.drop_index(op.f("ix_integration_runs_resource_type"), table_name="integration_runs")
    op.drop_index(op.f("ix_integration_runs_provider_request_id"), table_name="integration_runs")
    op.drop_index(op.f("ix_integration_runs_idempotency_key"), table_name="integration_runs")
    op.drop_index(op.f("ix_integration_runs_correlation_id"), table_name="integration_runs")
    op.drop_index(op.f("ix_integration_runs_connection_id"), table_name="integration_runs")
    op.drop_table("integration_runs")
    op.drop_index(
        op.f("ix_integration_connections_token_expires_at"), table_name="integration_connections"
    )
    op.drop_index(op.f("ix_integration_connections_store_id"), table_name="integration_connections")
    op.drop_index(op.f("ix_integration_connections_status"), table_name="integration_connections")
    op.drop_index(op.f("ix_integration_connections_provider"), table_name="integration_connections")
    op.drop_index(
        op.f("ix_integration_connections_external_account_id"), table_name="integration_connections"
    )
    op.drop_table("integration_connections")
    op.drop_index(op.f("ix_stores_store_code"), table_name="stores")
    op.drop_index(op.f("ix_stores_mall_id"), table_name="stores")
    op.drop_table("stores")
    # ### end Alembic commands ###
